# https://stackoverflow.com/questions/65354567/restore-backup-file-created-with-copy
#
---
- name: Restore latest file backup
  hosts: localhost
  gather_facts: false

  vars:
    my_file: /tmp/test_restore/toto.txt

  tasks:
    - name: "Find all backups for {{ my_file }}"
      ansible.builtin.find:
        recurse: no
        paths:
          - "{{ my_file | dirname }}"
        patterns:
          - '{{ my_file | basename }}\..*~'
        use_regex: true
      register: find_backup

    - name: Select the latest backup found on disk
      ansible.builtin.set_fact:
        latest_backup: "{{ (find_backup.files | sort(attribute='mtime') | last).path }}"

    - name: Show the latest selected backup
      ansible.builtin.debug:
        var: latest_backup

    - name: "Restore latest backup of {{ my_file }}"
      ansible.builtin.copy:
        src: "{{ latest_backup }}"
        remote_src: true
        dest: "{{ my_file }}"
